### PR TITLE
Added 2016 UK holidays

### PR DESCRIPTION
**Pull request by tobymarsden**

### CODE REVIEW

**Comment by greysteil** [comment]
:+1: thanks! Are you up for updating the TARGET holidays (asterisk-ed dates at https://www.ecb.europa.eu/home/html/holidays.en.html) too? If so I'll bump the version.

**Comment by tobymarsden** [comment]
@greysteil -- good stuff, thanks for the quick response!

**Comment by greysteil** [comment]
:+1:

**Comment by greysteil** [comment]
Pushed a tag but it looks like we need @hmarr to push to rubygems.

Harry - can you do the honours?

**Comment by hmarr** [comment]
1.5.0 pushed to Rubygems

**Pull request merged**
