### PR TITLE
Add "working_dates" option to handle case when some weekend day stated to be a work day.

### PR DESCRIPTION
**Pull request by relev**

### CODE REVIEW

**Comment by ojab** [comment]
I'm also interested in this functionality, it there anything that should be done to get it merged (except fixing trivial merge conflict of course)?

**Comment by timrogers** [comment]
Sorry for not reviewing this before - I didn't spot it.

What is the use case for having "working dates" which are in fact work days? I'd like to understand the reasoning a bit more so I can understand if there's a better way. (An answer from either of you, @relev or @ojab, would be helpful.)

**Comment by ojab** [comment]
It's a weekend days that are actually a working days. It's used here to make consequence holidays longer:
 for example this year 30th of April is Monday and there are holidays on 1-2 May, so 28th of April (Saturday) is made working date and 30th of April is made also a holiday.
So we have four conseq. holidays (from 29th of April to 2nd of May) instead of weekend on 28-29 of April, working monday on 30th of April and holidays on 1-2 May.

I've noticed that there is no specs for actual calculations, so I'll send the PR with specs added and merge conflicts resolved later today.

**Comment by timrogers** [comment]
That makes sense - it sounds like basically, they're the opposite of "holidays" (i.e. holidays are days which would normally be working days but aren't; these are days which would normally not be working days, but are). Feel free to go for it.

**Comment by ojab** [comment]
Done, https://github.com/gocardless/business/pull/26

**Comment by ojab** [comment]
@relev, I would be happy if you'll check that I've copypasted russian calendar from consultant correctly.

**Comment by ojab** [comment]
I assume that this PR can be closed now.

**Pull request closed without merging**
